### ISSUE TITLE
GEMINI3D+HWM compilation Vega

### ISSUE THREAD

**Issue by paulinchin** [gemini3d/gemini3d#84]
Trying to compile GEMINI3D with HWM-14 on Vega.

Modules loaded:
gcc/8.3.0 
openmpi/gcc8/64/3.1.2

Commands:
/home1/pineyrob/cmake-3.22.1-linux-x86_64/bin/cmake -B build -Dhwm14=true
/home1/pineyrob/cmake-3.22.1-linux-x86_64/bin/cmake cmake --build build -j

[100%] Linking Fortran executable ../gemini.bin
../libgemini3d.a(hwm_interface.f90.o): In function `__hwm_interface_MOD_dwm_07_r32':
hwm_interface.f90:(.text+0x1b): undefined reference to `dwm07_'
../libgemini3d.a(hwm_interface.f90.o): In function `__hwm_interface_MOD_dwm_07_r64':
hwm_interface.f90:(.text+0x9e): undefined reference to `dwm07_'
../libgemini3d.a(hwm_interface.f90.o): In function `__hwm_interface_MOD_hwm_14_r32':
hwm_interface.f90:(.text+0xf7): undefined reference to `hwm14_'
../libgemini3d.a(hwm_interface.f90.o): In function `__hwm_interface_MOD_hwm_14_r64':
hwm_interface.f90:(.text+0x198): undefined reference to `hwm14_'
collect2: error: ld returned 1 exit status
gmake[2]: *** [gemini.bin] Error 1
gmake[1]: *** [src/CMakeFiles/gemini.bin.dir/all] Error 2
gmake: *** [all] Error 2 (edited)

**Comment by mattzett** [comment]
Works on CentOS stream 8 x86, gcc 8.5 (edited) 

mattzett  16 hours ago
Centos stream 8 x86, oneapi 2021.4 works (edited) 

mattzett  16 hours ago
Ubuntu 20.04 x86, gcc 9.3 gives this error. (edited) 

mattzett  16 hours ago
gcc 11.2 on Fedora 34 ARM64 works fine (edited) 

mattzett  16 hours ago
ubuntu 20.04 x86, intel 2021.4 also fails with same error (edited) 

mattzett  16 hours ago
ubuntu 20.04 ARM64, gcc 9.3 gives this failure:
/usr/bin/ld: ../lib/libblacs.a(BI_Rsend.c.o): undefined reference to symbol 'MPI_Rsend'
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/openmpi/lib/libmpi.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gemini.bin.dir/build.make:228: gemini.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:1915: src/CMakeFiles/gemini.bin.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by mattzett** [comment]
Also work on intel MAC gcc 12.1

**Comment by scivision** [comment]
I updated the linking and package and [added an HWM14 CI case](https://github.com/gemini3d/gemini3d/commit/8d553f544d87cc6743f4416937b6abed72f38ae0)  

I think HWM14 should build OK now, please reopen issue if not.

**Comment by paulinchin** [comment]
I was able to compile
/home1/pineyrob/cmake-3.22.1-linux-x86_64/bin/cmake -B build -Dhwm14=true
/home1/pineyrob/cmake-3.22.1-linux-x86_64/bin/cmake --build build -j

but while running, it gives me errors:

/home1/pineyrob/.bash_profile: line 3: -S: command not found
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMALNote: The following floating-point exceptions are signalling: IEE$
ERROR STOP Can not find file hwm123114.bin

ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP Can not find file hwm123114.bin
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

**Comment by scivision** [comment]
Paul I've repackages how HWM14 works since then. This is no longer an issue when not using HWM14. 
I do need to reimplement how HWM14 works when it is used.
